### PR TITLE
Fix up incompatible pointer issues

### PR DESCRIPTION
**Pull request by glguy**
This relates to #88 and is what I'm using locally to get HsOpenSSL working again.

### CODE REVIEW

**Comment by erikd** [comment]
Any ETA for this being merged and a new release on Hackage?

**Review by Kleidukos — APPROVED** [review]
Thanks a lot!

**Comment by Kleidukos** [comment]
@vshabanov @andreasabel could you perhaps handle the Hackage release?

**Comment by erikd** [comment]
This has been released to Hackage as `0.11.7.8` but building that with `ghc-9.8.2` on Linux still fails.

The code in the repo still has a version of  `0.11.7.7`.

**Pull request merged**
